#!/bin/bash
# Script de ayuda para comandos de base de datos

echo "========================================"
echo "  COMANDOS ÚTILES PARA BASE DE DATOS"
echo "========================================"
echo ""
echo "🔹 VER ESTADO:"
echo "  docker-compose ps"
echo "  docker-compose logs database"
echo ""
echo "🔹 CONECTARSE A PostgreSQL:"
echo "  docker-compose exec database psql -U tudiabetes_user -d tudiabetes"
echo ""
echo "🔹 COMANDOS SQL ÚTILES (una vez conectado):"
echo "  \\dt                    - Listar tablas"
echo "  \\d users              - Ver estructura de tabla"
echo "  SELECT * FROM users;   - Ver usuarios"
echo "  SELECT * FROM posts;   - Ver publicaciones"
echo ""
echo "🔹 SCRIPTS DISPONIBLES:"
echo "  database/scripts/backup.sh        - Crear backup"
echo "  database/scripts/restore.sh       - Restaurar backup"
echo "  database/scripts/reset.sh         - Resetear BD"
echo "  database/scripts/list_backups.sh  - Listar backups"
echo "  database/scripts/help.sh          - Mostrar esta ayuda"
echo ""
echo "🔹 REINICIAR SERVICIOS:"
echo "  docker-compose restart backend"
echo "  docker-compose restart database"
echo ""
echo "🔹 VER LOGS:"
echo "  docker-compose logs -f backend"
echo "  docker-compose logs -f database"
echo ""