# backend/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Instalar nodemon para recarga automática
RUN npm install -g nodemon

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["nodemon", "src/index.js"]