FROM node:18-alpine

WORKDIR /app

# Instalar nodemon globalmente
RUN npm install -g nodemon

# Copiar package.json y package-lock.json (si existe)
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

EXPOSE 3000

CMD ["nodemon", "src/index.js"]